import React, { useState } from 'react';
import { useAether } from '../../context/AetherContextValue';
import { IconX, IconCheckCircle, IconZap, IconCopy, IconAlertTriangle } from '../common/Icons';

interface IncidentPostMortemModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const IncidentPostMortemModal: React.FC<IncidentPostMortemModalProps> = ({ isOpen, onClose }) => {
  const { currentProject, createIssue, t } = useAether();

  const [incidentTitle, setIncidentTitle] = useState('INC-402: API Gateway 504 Timeout Outage');
  const [severity] = useState<'P1' | 'P2' | 'P3'>('P1');
  const [durationMins] = useState(42);
  const [copied, setCopied] = useState(false);
  const [actionItemsCreated, setActionItemsCreated] = useState(false);

  if (!isOpen) return null;

  const fiveWhys = [
    { why: '1. Why did the API Gateway return 504 Timeouts?', cause: 'Database connection pool was exhausted by unindexed query spikes.' },
    { why: '2. Why was the DB connection pool exhausted?', cause: 'A missing composite index on `user_sessions` forced full table scans.' },
    { why: '3. Why was the index missing in production?', cause: 'Migration script v1.3.8 omitted the CREATE INDEX statement.' },
    { why: '4. Why did CI/CD migration tests not catch it?', cause: 'Test environment used a small mock database (100 rows vs 2M prod rows).' },
    { why: '5. Why was mock data size insufficient?', cause: 'Load testing suite lacked large-scale staging data benchmarks.' },
  ];

  const actionItems = [
    { key: 'PREV-1', summary: 'Add composite index to user_sessions table', assignee: 'Marcus Vance' },
    { key: 'PREV-2', summary: 'Configure DB Connection Pool Circuit Breaker', assignee: 'Alex Rivera' },
    { key: 'PREV-3', summary: 'Upgrade Staging DB load test dataset to 1M rows', assignee: 'Sarah Chen' },
  ];

  const postMortemMarkdown = `
# Incident Post-Mortem Report - ${incidentTitle}
**Project:** ${currentProject.name} (${currentProject.key})
**Severity:** ${severity} | **Duration:** ${durationMins} mins | **Date:** ${new Date().toLocaleDateString()}

## AI 5-Whys Root Cause Analysis
${fiveWhys.map(w => `- **${w.why}**\n  ↳ ${w.cause}`).join('\n')}

## Preventive Action Items
${actionItems.map(a => `- [ ] **[${a.key}]** ${a.summary} (@${a.assignee})`).join('\n')}

---
*Generated by AetherPulse SRE AI Engine*
`.trim();

  const handleCopyReport = () => {
    navigator.clipboard.writeText(postMortemMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleCreateActionItems = () => {
    actionItems.forEach(item => {
      createIssue({
        summary: `[Post-Mortem] ${item.summary}`,
        type: 'task',
        priority: 'highest',
        status: 'todo',
        storyPoints: 3,
        description: `Preventive action item from ${incidentTitle}`,
      });
    });
    setActionItemsCreated(true);
    setTimeout(() => {
      setActionItemsCreated(false);
      onClose();
    }, 2000);
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content postmortem-modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div className="modal-title-group">
            <span className="release-icon"><IconAlertTriangle size={20} /></span>
            <div>
              <h2 className="modal-title">{t('postMortemModalTitle')}</h2>
              <p className="modal-subtitle">
                Structured 5-Whys diagnosis & preventive action item generator for [{currentProject.key}]
              </p>
            </div>
          </div>
          <button className="btn-icon close-btn" onClick={onClose}>
            <IconX />
          </button>
        </div>

        <div className="modal-body postmortem-modal-body">
          {/* Incident Meta Row */}
          <div className="pm-meta-row">
            <input
              type="text"
              value={incidentTitle}
              onChange={(e) => setIncidentTitle(e.target.value)}
              className="pm-title-input"
            />
            <div className="pm-pills">
              <span className={`pm-sev-badge ${severity.toLowerCase()}`}>{t('severity')}: {severity}</span>
              <span className="pm-time-badge">{t('outageDuration')}: {durationMins} mins</span>
            </div>
          </div>

          {/* AI 5-Whys Analysis Section */}
          <div className="pm-section">
            <div className="pm-section-header">
              <IconZap size={18} color="#6366f1" />
              <span>{t('ai5WhysChain')}</span>
            </div>
            <div className="whys-list">
              {fiveWhys.map((w, idx) => (
                <div key={idx} className="why-item-card">
                  <div className="why-q">{w.why}</div>
                  <div className="why-a">↳ {w.cause}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Preventive Action Items Matrix */}
          <div className="pm-section">
            <div className="pm-section-header">
              <span>{t('preventiveActionItems')}</span>
            </div>
            <div className="pm-actions-grid">
              {actionItems.map((item, idx) => (
                <div key={idx} className="pm-action-card">
                  <span className="pm-act-key">{item.key}</span>
                  <span className="pm-act-desc">{item.summary}</span>
                  <span className="pm-act-owner">@{item.assignee}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="modal-footer">
          <button className="btn-secondary" onClick={handleCopyReport}>
            <IconCopy size={16} /> {copied ? t('copiedReport') : t('copyMarkdownReport')}
          </button>
          <button
            className="btn-primary"
            onClick={handleCreateActionItems}
            disabled={actionItemsCreated}
          >
            {actionItemsCreated ? (
              <>
                <IconCheckCircle /> {t('createdBacklogTasksSuccess')}
              </>
            ) : (
              <>
                {t('convertActionItemsToTasks')}
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
