import React, { useState, useMemo } from 'react';
import { useAether } from '../../context/AetherContextValue';
import { IconX, IconCopy, IconCheckCircle, IconDownload, IconReports } from '../common/Icons';

interface RetroReportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const RetroReportModal: React.FC<RetroReportModalProps> = ({ isOpen, onClose }) => {
  const { sprints, retrospectiveItems, t } = useAether();

  const [selectedSprintId, setSelectedSprintId] = useState<string>(
    sprints.find((s) => s.status === 'active')?.id || sprints[0]?.id || ''
  );
  const [copied, setCopied] = useState(false);

  const selectedSprint = useMemo(() => {
    return sprints.find((s) => s.id === selectedSprintId) || sprints[0] || null;
  }, [sprints, selectedSprintId]);

  const wentWellItems = useMemo(
    () => retrospectiveItems.filter((i) => i.type === 'went_well'),
    [retrospectiveItems]
  );
  const toImproveItems = useMemo(
    () => retrospectiveItems.filter((i) => i.type === 'to_improve'),
    [retrospectiveItems]
  );
  const actionItems = useMemo(
    () => retrospectiveItems.filter((i) => i.type === 'action_item'),
    [retrospectiveItems]
  );

  const totalVotes = useMemo(() => {
    return retrospectiveItems.reduce((acc, item) => acc + (item.votes || 0), 0);
  }, [retrospectiveItems]);

  const sentimentScore = useMemo(() => {
    const total = retrospectiveItems.length || 1;
    const positiveRatio = (wentWellItems.length / total) * 100;
    return Math.round(positiveRatio);
  }, [retrospectiveItems, wentWellItems]);

  if (!isOpen || !selectedSprint) return null;

  const reportMarkdown = `### ${t('retroReportTitle')}
**${t('sprint')}:** ${selectedSprint.name}
**${t('goalPrefix')}:** ${selectedSprint.goal || '-'}
**${t('sentimentIndex')}:** ${sentimentScore}% ${t('positiveSentiment')}
**${t('votesCast')}:** ${totalVotes}

---

#### ${t('wentWell')} (${wentWellItems.length})
${wentWellItems.map((item) => `- **[+${item.votes} votes]** ${item.content}`).join('\n')}

#### ${t('toImprove')} (${toImproveItems.length})
${toImproveItems.map((item) => `- **[+${item.votes} votes]** ${item.content}`).join('\n')}

#### ${t('actionItems')} (${actionItems.length})
${actionItems.map((item) => `- [ ] **[+${item.votes} votes]** ${item.content}`).join('\n')}

---
*Generated by Aether Pulse AI Agile Assistant*`;

  const handleCopyReport = () => {
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportDownload = () => {
    const blob = new Blob([reportMarkdown], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `Retro_Summary_${selectedSprint.name.replace(/\s+/g, '_')}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className="modal-content retro-report-modal"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="modal-header">
          <div className="modal-title-group">
            <span className="release-icon"><IconReports size={20} /></span>
            <div>
              <h2 className="modal-title">{t('retroReportTitle')}</h2>
            </div>
          </div>
          <button className="btn-icon close-btn" onClick={onClose}>
            <IconX />
          </button>
        </div>

        <div className="modal-body retro-modal-body">
          {/* Target Sprint Selector & Sentiment Banner */}
          <div className="retro-top-row">
            <div className="retro-sprint-select">
              <label>{t('selectSprint')}:</label>
              <select
                value={selectedSprint.id}
                onChange={(e) => setSelectedSprintId(e.target.value)}
                className="retro-dropdown"
              >
                {sprints.map((s) => (
                  <option key={s.id} value={s.id}>
                    {s.name} ({s.status.toUpperCase()})
                  </option>
                ))}
              </select>
            </div>

            <div className="sentiment-index-box">
              <span>{t('sentimentIndex')}:</span>
              <strong className={sentimentScore >= 60 ? 'good' : 'warning'}>
                {sentimentScore}% {t('positiveSentiment')}
              </strong>
            </div>
          </div>

          {/* Retrospective Category Counters */}
          <div className="retro-metrics-grid">
            <div className="retro-metric-card green">
              <span className="retro-val">{wentWellItems.length}</span>
              <span className="retro-lbl">{t('wentWell')}</span>
            </div>
            <div className="retro-metric-card yellow">
              <span className="retro-val">{toImproveItems.length}</span>
              <span className="retro-lbl">{t('toImprove')}</span>
            </div>
            <div className="retro-metric-card blue">
              <span className="retro-val">{actionItems.length}</span>
              <span className="retro-lbl">{t('actionItems')}</span>
            </div>
            <div className="retro-metric-card purple">
              <span className="retro-val">{totalVotes}</span>
              <span className="retro-lbl">{t('votesCast')}</span>
            </div>
          </div>

          {/* Report Preview Code Box */}
          <div className="retro-preview-container">
            <div className="retro-preview-header">
              <span>{t('markdownPreview')} ({selectedSprint.name})</span>
              <button className="btn-copy-small" onClick={handleCopyReport}>
                {copied ? <IconCheckCircle /> : <IconCopy />}
                {copied ? ` ${t('copied')}` : ` ${t('copyMarkdown')}`}
              </button>
            </div>
            <pre className="retro-pre">{reportMarkdown}</pre>
          </div>
        </div>

        <div className="modal-footer">
          <button className="btn-secondary" onClick={onClose}>
            {t('close')}
          </button>
          <button className="btn-primary" onClick={handleExportDownload}>
            <IconDownload /> {t('exportRetro')}
          </button>
        </div>
      </div>
    </div>
  );
};
