import React, { useState, useMemo } from 'react';
import { useAether } from '../../context/AetherContextValue';
import { IconX, IconCopy, IconCheckCircle, IconDownload } from '../common/Icons';

interface RetroReportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const RetroReportModal: React.FC<RetroReportModalProps> = ({ isOpen, onClose }) => {
  const { sprints, retrospectiveItems } = useAether();

  const [selectedSprintId, setSelectedSprintId] = useState<string>(
    sprints.find((s) => s.status === 'active')?.id || sprints[0]?.id || ''
  );
  const [copied, setCopied] = useState(false);

  const selectedSprint = useMemo(() => {
    return sprints.find((s) => s.id === selectedSprintId) || sprints[0] || null;
  }, [sprints, selectedSprintId]);

  const wentWellItems = useMemo(
    () => retrospectiveItems.filter((i) => i.type === 'went_well'),
    [retrospectiveItems]
  );
  const toImproveItems = useMemo(
    () => retrospectiveItems.filter((i) => i.type === 'to_improve'),
    [retrospectiveItems]
  );
  const actionItems = useMemo(
    () => retrospectiveItems.filter((i) => i.type === 'action_item'),
    [retrospectiveItems]
  );

  const totalVotes = useMemo(() => {
    return retrospectiveItems.reduce((acc, item) => acc + (item.votes || 0), 0);
  }, [retrospectiveItems]);

  const sentimentScore = useMemo(() => {
    const total = retrospectiveItems.length || 1;
    const positiveRatio = (wentWellItems.length / total) * 100;
    return Math.round(positiveRatio);
  }, [retrospectiveItems, wentWellItems]);

  if (!isOpen || !selectedSprint) return null;

  const reportMarkdown = `### 📊 Agile Sprint Retrospective Executive Summary
**Sprint:** ${selectedSprint.name}
**Sprint Goal:** ${selectedSprint.goal || 'Continuous Delivery & Performance Improvement'}
**Team Sentiment Index:** ${sentimentScore}% Positive (${wentWellItems.length} Wins / ${toImproveItems.length} Areas to Improve)
**Total Community Votes Cast:** ${totalVotes} votes

---

#### 🟢 What Went Well (${wentWellItems.length} Items)
${wentWellItems.map((item) => `- **[+${item.votes} votes]** ${item.content}`).join('\n')}

#### 🟡 Areas to Improve (${toImproveItems.length} Items)
${toImproveItems.map((item) => `- **[+${item.votes} votes]** ${item.content}`).join('\n')}

#### 🎯 Key Action Items & Ownership (${actionItems.length} Items)
${actionItems.map((item) => `- [ ] **[+${item.votes} votes]** ${item.content}`).join('\n')}

---
*Generated by Aether Pulse AI Agile Assistant*`;

  const handleCopyReport = () => {
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportDownload = () => {
    const blob = new Blob([reportMarkdown], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `Retro_Summary_${selectedSprint.name.replace(/\s+/g, '_')}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className="modal-content retro-report-modal"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="modal-header">
          <div className="modal-title-group">
            <span className="release-icon">📊</span>
            <div>
              <h2 className="modal-title">Sprint Retrospective AI Executive Report</h2>
              <p className="modal-subtitle">
                Synthesize sprint wins, retrospective insights & action items for leadership
              </p>
            </div>
          </div>
          <button className="btn-icon close-btn" onClick={onClose}>
            <IconX />
          </button>
        </div>

        <div className="modal-body retro-modal-body">
          {/* Target Sprint Selector & Sentiment Banner */}
          <div className="retro-top-row">
            <div className="retro-sprint-select">
              <label>Select Sprint:</label>
              <select
                value={selectedSprint.id}
                onChange={(e) => setSelectedSprintId(e.target.value)}
                className="retro-dropdown"
              >
                {sprints.map((s) => (
                  <option key={s.id} value={s.id}>
                    {s.name} ({s.status.toUpperCase()})
                  </option>
                ))}
              </select>
            </div>

            <div className="sentiment-index-box">
              <span>Sentiment Index:</span>
              <strong className={sentimentScore >= 60 ? 'good' : 'warning'}>
                {sentimentScore}% Positive
              </strong>
            </div>
          </div>

          {/* Retrospective Category Counters */}
          <div className="retro-metrics-grid">
            <div className="retro-metric-card green">
              <span className="retro-val">{wentWellItems.length}</span>
              <span className="retro-lbl">🟢 What Went Well</span>
            </div>
            <div className="retro-metric-card yellow">
              <span className="retro-val">{toImproveItems.length}</span>
              <span className="retro-lbl">🟡 To Improve</span>
            </div>
            <div className="retro-metric-card blue">
              <span className="retro-val">{actionItems.length}</span>
              <span className="retro-lbl">🎯 Action Items</span>
            </div>
            <div className="retro-metric-card purple">
              <span className="retro-val">{totalVotes}</span>
              <span className="retro-lbl">🗳️ Votes Cast</span>
            </div>
          </div>

          {/* Report Preview Code Box */}
          <div className="retro-preview-container">
            <div className="retro-preview-header">
              <span>Markdown Report Preview ({selectedSprint.name})</span>
              <button className="btn-copy-small" onClick={handleCopyReport}>
                {copied ? <IconCheckCircle /> : <IconCopy />}
                {copied ? ' Copied!' : ' Copy Markdown'}
              </button>
            </div>
            <pre className="retro-pre">{reportMarkdown}</pre>
          </div>
        </div>

        <div className="modal-footer">
          <button className="btn-secondary" onClick={onClose}>
            Close
          </button>
          <button className="btn-primary" onClick={handleExportDownload}>
            <IconDownload /> Export Retro (.md)
          </button>
        </div>
      </div>
    </div>
  );
};
