import { PrintRequest, Printer, AuditLog, KpiSummary } from '../types'

export const mockKpiData: KpiSummary = {
  totalRequests: 1420,
  pendingApprovals: 12,
  activePrinters: 12,
  totalPrinters: 12,
  paperSavingsPercent: 28.5,
}

export const mockPrintRequests: PrintRequest[] = [
  {
    id: 'PR-2026-001',
    documentName: '2026_Q3_Financial_Report.docx',
    pageCount: 45,
    copyCount: 2,
    securityLevel: 'CONFIDENTIAL',
    status: 'PENDING',
    requesterName: '김민수 대리',
    requesterDepartment: '재무회계팀',
    createdAt: '2026-07-23 16:30',
  },
  {
    id: 'PR-2026-002',
    documentName: 'Project_Alpha_Architecture_v2.pdf',
    pageCount: 12,
    copyCount: 1,
    securityLevel: 'RESTRICTED',
    status: 'APPROVED',
    requesterName: '박서연 과장',
    requesterDepartment: '기술개발본부',
    approverName: '이동현 팀장',
    createdAt: '2026-07-23 15:10',
  },
  {
    id: 'PR-2026-003',
    documentName: 'Marketing_Flyer_Draft.ai',
    pageCount: 4,
    copyCount: 50,
    securityLevel: 'PUBLIC',
    status: 'REJECTED',
    requesterName: '정수진 사원',
    requesterDepartment: '마케팅팀',
    approverName: '이동현 팀장',
    rejectionReason: '컬러 50장 출력 사유 부족. 디지털 문서 배포 권장',
    createdAt: '2026-07-23 14:05',
  },
  {
    id: 'PR-2026-004',
    documentName: 'Employee_Evaluation_2026.xlsx',
    pageCount: 8,
    copyCount: 1,
    securityLevel: 'CONFIDENTIAL',
    status: 'PENDING',
    requesterName: '최현우 차장',
    requesterDepartment: '인사총무팀',
    createdAt: '2026-07-23 13:45',
  },
]

export const mockPrinters: Printer[] = [
  {
    id: 'PRT-01',
    name: '본사 4층 개발팀 복합기',
    modelName: 'HP LaserJet Pro M404dn',
    ipAddress: '192.168.1.150',
    location: '본사 4F A구역',
    status: 'ONLINE',
    blackTonerLevel: 85,
    paperLevel: 90,
    activeJobCount: 0,
    lastCheckedAt: '방금 전',
  },
  {
    id: 'PRT-02',
    name: '본사 3층 임원실 복합기',
    modelName: 'Xerox VersaLink C400',
    ipAddress: '192.168.1.151',
    location: '본사 3F B구역',
    status: 'LOW_TONER',
    blackTonerLevel: 15,
    colorTonerLevel: 30,
    paperLevel: 40,
    activeJobCount: 1,
    lastCheckedAt: '1분 전',
  },
  {
    id: 'PRT-03',
    name: '본사 2층 마케팅 고속 출력기',
    modelName: 'Canon imageRUNNER ADVANCE',
    ipAddress: '192.168.1.152',
    location: '본사 2F C구역',
    status: 'PRINTING',
    blackTonerLevel: 60,
    colorTonerLevel: 72,
    paperLevel: 65,
    activeJobCount: 3,
    lastCheckedAt: '방금 전',
  },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'AUD-9901',
    action: 'APPROVAL_GRANTED',
    actorName: '이동현 팀장',
    targetResource: 'PR-2026-002 (Project_Alpha.pdf)',
    details: '기술개발본부 승인 완료 (12장 1부)',
    ipAddress: '10.0.4.12',
    createdAt: '2026-07-23 15:10:02',
  },
  {
    id: 'AUD-9900',
    action: 'PRINT_REQUEST_CREATED',
    actorName: '김민수 대리',
    targetResource: 'PR-2026-001 (Financial_Report.docx)',
    details: '기밀 문서 출력 승인 요청 생성',
    ipAddress: '10.0.2.88',
    createdAt: '2026-07-23 16:30:15',
  },
]
